version: '3.4'

services:
   basketdb:
    image: redis
    ports:
     - "6379:6379"

   sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    hostname:  
     "localhostdc"   
    environment:
      MSSQL_SA_PASSWORD: "MooqPassword@123"
      ACCEPT_EULA: "Y"   
      

   rabbitmq: # login guest:guest
    image: rabbitmq:3-management
    hostname: "rabbitmq"
    labels:
      NAME: "rabbitmq"
    ports:    
     - "15672:15672"

   basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    ports:
     - "51320:51320"
    build:
      context: .
      dockerfile: Services/Basket.Api/Dockerfile

   catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    ports:
     - "5002:5002"
    build:
      context: .
      dockerfile: Services/CatalogService/Catalog.API.UI/Dockerfile


   order.api:
    image: ${DOCKER_REGISTRY-}orderapi
    ports:
     - "5001:5001"
    build:
      context: .
      dockerfile: Services/Order/Order.API/Dockerfile


   identityservercognito:
    image: ${DOCKER_REGISTRY-}identityservercognito
    ports:
     - "51288:51288"
    build:
      context: .
      dockerfile: Infrastructure/IdentityServerCognito/Dockerfile

