name: deploy to ecr
'on':
  push : 
   branches:
        [ "master" ]
jobs:
  build:
    name: moq_build_image
    runs-on: ubuntu-latest    
    permissions:
           packages: write
    steps:
      - name: check out code
        uses: actions/checkout@v4
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          context: .
          aws-access-key-id: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          aws-secret-access-key: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
          aws-region: eu-west-2
      - name: Login to Amazon ECR
        id: login-ecr 
        uses: aws-actions/amazon-ecr-login@v1
      - name: 'Build, tag, and push image to Amazon ECR for IdentityserverCognito'
        env:
          ECR_REGISTRY: '${{ steps.login-ecr.outputs.registry }}'
          ECR_REPOSITORY: mooqdocker
          IMAGE_TAG: mooq_image_tag
        run: |
          docker build -f ./Infrastructure/IdentityServerCognito/Dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
